In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [5]:
df = pd.read_excel("healthcare_realistic_dataset_515_rows.xlsx")

In [6]:
df.head()

,Patient_ID,Age,Gender,Blood_Group,Height_cm,Weight_kg,BMI,Disease,Department,City,Admission_Date,Discharge_Date,Treatment_Cost,Insurance_Status,Outcome
0,P0001,24.0,Male,A+,162,56.0,21.3,Migraine,Pulmonology,Kolkata,2025-07-28,2025-08-06,92083.0,No,Recovered
1,P0002,38.0,Male,B+,153,88.0,37.6,Diabetes,General Medicine,Hyderabad,2025-10-15,2025-10-26,27967.0,No,Recovered
2,P0003,18.0,Male,B+,165,102.0,37.5,Asthma,Cardiology,Delhi,2025-02-22,2025-02-24,243852.0,No,Critical
3,P0004,79.0,Female,O-,161,105.0,40.5,COVID-19,Pulmonology,Patna,2025-01-19,2025-01-29,143169.0,No,Recovered
4,P0005,68.0,Female,O+,186,110.0,31.8,Arthritis,Pulmonology,Pune,2025-08-11,2025-08-29,227125.0,Yes,Critical

In [7]:
df.shape

(515, 15)

In [8]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Blood_Group', 'Height_cm', 'Weight_kg',
       'BMI', 'Disease', 'Department', 'City', 'Admission_Date',
       'Discharge_Date', 'Treatment_Cost', 'Insurance_Status', 'Outcome'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Patient_ID        515 non-null    object
 1   Age               489 non-null    float64
 2   Gender            489 non-null    object
 3   Blood_Group       489 non-null    object
 4   Height_cm         515 non-null    int64
 5   Weight_kg         490 non-null    float64
 6   BMI               515 non-null    float64
 7   Disease           489 non-null    object
 8   Department        515 non-null    object
 9   City              515 non-null    object
 10  Admission_Date    515 non-null    object
 11  Discharge_Date    515 non-null    object
 12  Treatment_Cost    488 non-null    float64
 13  Insurance_Status  515 non-null    object
 14  Outcome           515 non-null    object
dtypes: float64(4), int64(1), object(10)
memory usage: 60.5+ KB

In [10]:
df.isnull().sum()

Patient_ID           0
Age                 26
Gender              26
Blood_Group         26
Height_cm            0
Weight_kg           25
BMI                  0
Disease             26
Department           0
City                 0
Admission_Date       0
Discharge_Date       0
Treatment_Cost      27
Insurance_Status     0
Outcome              0
dtype: int64

In [11]:
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"])
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Patient_ID        515 non-null    object
 1   Age               489 non-null    float64
 2   Gender            489 non-null    object
 3   Blood_Group       489 non-null    object
 4   Height_cm         515 non-null    int64
 5   Weight_kg         490 non-null    float64
 6   BMI               515 non-null    float64
 7   Disease           489 non-null    object
 8   Department        515 non-null    object
 9   City              515 non-null    object
 10  Admission_Date    515 non-null    datetime64[ns]
 11  Discharge_Date    515 non-null    datetime64[ns]
 12  Treatment_Cost    488 non-null    float64
 13  Insurance_Status  515 non-null    object
 14  Outcome           515 non-null    object
dtypes: datetime64[ns](2), float64(4), int64(1), object(8)
memory usage: 60.5+ KB

In [15]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Weight_kg"] = df["Weight_kg"].fillna(df["Weight_kg"].median())
df["Treatment_Cost"] = df["Treatment_Cost"].fillna(df["Treatment_Cost"].median())

In [16]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
df["Blood_Group"] = df["Blood_Group"].fillna(df["Blood_Group"].mode()[0])
df["Disease"] = df["Disease"].fillna(df["Disease"].mode()[0])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Patient_ID        515 non-null    object
 1   Age               515 non-null    float64
 2   Gender            515 non-null    object
 3   Blood_Group       515 non-null    object
 4   Height_cm         515 non-null    int64
 5   Weight_kg         515 non-null    float64
 6   BMI               515 non-null    float64
 7   Disease           515 non-null    object
 8   Department        515 non-null    object
 9   City              515 non-null    object
 10  Admission_Date    515 non-null    datetime64[ns]
 11  Discharge_Date    515 non-null    datetime64[ns]
 12  Treatment_Cost    515 non-null    float64
 13  Insurance_Status  515 non-null    object
 14  Outcome           515 non-null    object
dtypes: datetime64[ns](2), float64(4), int64(1), object(8)
memory usage: 60.5+ KB

In [18]:
df.duplicated().sum()

np.int64(15)

In [19]:
df = df.drop_duplicates()

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.shape

(500, 15)

In [22]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [23]:
df["Blood_Group"].unique()

array(['A+', 'B+', 'O-', 'O+', 'AB-', 'AB+', 'A-', 'B-'], dtype=object)

In [24]:
df["Insurance_Status"].unique()

array(['No', 'Yes'], dtype=object)

In [25]:
df["Outcome"].unique()

array(['Recovered', 'Critical', 'Ongoing'], dtype=object)

In [26]:
df.reset_index(drop=True, inplace=True)

In [27]:
df.to_excel("cleaned_healthcare_dataset.xlsx", index=False)

In [ ]:
# Business Analysis Questions

In [ ]:
1. Which disease contributes the highest total treatment cost?

In [28]:
disease_cost = df.groupby("Disease")["Treatment_Cost"].sum().sort_values(ascending=False)
disease_cost

Disease
Asthma           10938576.5
Arthritis         8235337.5
Heart Disease     8223494.5
Pneumonia         6954734.5
COVID-19          6902742.5
Diabetes          6776360.0
Migraine          6733805.0
Hypertension      6462863.0
Name: Treatment_Cost, dtype: float64

In [ ]:
2. Which department generates the highest revenue?

In [29]:
department_revenue = df.groupby("Department")["Treatment_Cost"].sum().sort_values(ascending=False)
department_revenue

Department
Neurology           11955993.5
Oncology            11577124.5
Cardiology          10006369.5
Pulmonology          9281318.0
Orthopedics          9274249.5
General Medicine     9132858.5
Name: Treatment_Cost, dtype: float64

In [ ]:
3. What is the average treatment cost by disease and insurance status?

In [30]:
avg_treatment_cost = (
    df.groupby(["Disease", "Insurance_Status"])["Treatment_Cost"]
      .mean()
      .round(2)
)
avg_treatment_cost

Disease        Insurance_Status
Arthritis      No                  131878.32
               Yes                 133469.72
Asthma         No                  114145.24
               Yes                 119368.34
COVID-19       No                  115925.29
               Yes                 135438.31
Diabetes       No                   94427.96
               Yes                 130946.45
Heart Disease  No                  117683.94
               Yes                 135622.64
Hypertension   No                  139989.50
               Yes                 123463.56
Migraine       No                  111590.06
               Yes                 148841.50
Pneumonia      No                  119453.21
               Yes                 102664.46
Name: Treatment_Cost, dtype: float64

In [ ]:
4. What percentage of total treatment costs are covered by insured patients?

In [31]:
total_cost = df["Treatment_Cost"].sum()

insured_cost = df[df["Insurance_Status"] == "Yes"]["Treatment_Cost"].sum()

insured_percentage = (insured_cost / total_cost) * 100

print(f"Percentage of treatment costs covered by insured patients: {insured_percentage:.2f}%")

Percentage of treatment costs covered by insured patients: 51.87%

In [ ]:
5. Which city has the highest average treatment cost per patient?

In [32]:
city_avg_cost = (
    df.groupby("City")["Treatment_Cost"]
      .mean()
      .sort_values(ascending=False)
      .round(2)
)
city_avg_cost

City
Delhi        138487.95
Bengaluru    128335.27
Kolkata      127367.13
Mumbai       123011.49
Hyderabad    119676.06
Patna        114257.26
Pune         108753.34
Name: Treatment_Cost, dtype: float64

In [ ]:
# Patient Demographics Analysis

In [ ]:
6. Which age group (18–30, 31–45, 46–60, 60+) contributes the highest healthcare expenditure?

In [35]:
bins = [18, 30, 45, 60, float('inf')]
labels = ["18-30", "31-45", "46-60", "60+"]

df["Age_Group"] = pd.cut(df["Age"], bins=bins, labels=labels, include_lowest=True)

df["Age_Group"].head()

0    18-30
1    31-45
2    18-30
3      60+
4      60+
Name: Age_Group, dtype: category
Categories (4, object): ['18-30' < '31-45' < '46-60' < '60+']

In [ ]:
7. What diseases are most common among different age groups?

In [37]:
disease_age_group = (
    df.groupby(["Age_Group", "Disease"], observed=False)
      .size()
      .reset_index(name="Patient_Count")
)

disease_age_group

   Age_Group        Disease  Patient_Count
0      18-30      Arthritis             13
1      18-30         Asthma             19
2      18-30       COVID-19             12
3      18-30       Diabetes              9
4      18-30  Heart Disease             10
5      18-30   Hypertension              9
6      18-30       Migraine             14
7      18-30      Pneumonia              9
8      31-45      Arthritis             14
9      31-45         Asthma             21
10     31-45       COVID-19             10
11     31-45       Diabetes             11
12     31-45  Heart Disease             15
13     31-45   Hypertension             11
14     31-45       Migraine              9
15     31-45      Pneumonia             11
16     46-60      Arthritis             20
17     46-60         Asthma             22
18     46-60       COVID-19             17
19     46-60       Diabetes             18
20     46-60  Heart Disease             20
21     46-60   Hypertension             14
22     46-60       Migraine             16
23     46-60      Pneumonia             16
24       60+      Arthritis             15
25       60+         Asthma             32
26       60+       COVID-19             16
27       60+       Diabetes             21
28       60+  Heart Disease             20
29       60+   Hypertension             15
30       60+       Migraine             14
31       60+      Pneumonia             26

In [ ]:
8. Is there a significant difference in treatment costs between male and female patients?

In [38]:
gender_cost = (
    df.groupby("Gender")["Treatment_Cost"]
      .mean()
      .round(2)
)
gender_cost

Gender
Female    124396.76
Male      120195.61
Name: Treatment_Cost, dtype: float64

In [ ]:
9. Which blood group has the highest incidence of critical outcomes?

In [39]:
critical_patients = df[df["Outcome"] == "Critical"]

blood_group_critical = (
    critical_patients.groupby("Blood_Group")
                     .size()
                     .sort_values(ascending=False)
)
blood_group_critical

Blood_Group
AB+    31
AB-    25
B+     23
O-     22
A+     20
B-     19
A-     16
O+     15
dtype: int64