In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

In [74]:
df = pd.read_csv("healthcare_realistic_dataset_515_rows.csv")

df.head()

,Patient_ID,Age,Gender,Blood_Group,Height_cm,Weight_kg,BMI,Disease,Department,City,Admission_Date,Discharge_Date,Treatment_Cost,Insurance_Status,Outcome
0,P0001,24.0,Male,A+,162,56.0,21.3,Migraine,Pulmonology,Kolkata,2025-07-28,2025-08-06,92083.0,No,Recovered
1,P0002,38.0,Male,B+,153,88.0,37.6,Diabetes,General Medicine,Hyderabad,2025-10-15,2025-10-26,27967.0,No,Recovered
2,P0003,18.0,Male,B+,165,102.0,37.5,Asthma,Cardiology,Delhi,2025-02-22,2025-02-24,243852.0,No,Critical
3,P0004,79.0,Female,O-,161,105.0,40.5,COVID-19,Pulmonology,Patna,2025-01-19,2025-01-29,143169.0,No,Recovered
4,P0005,68.0,Female,O+,186,110.0,31.8,Arthritis,Pulmonology,Pune,2025-08-11,2025-08-29,227125.0,Yes,Critical

In [75]:
df.shape

(515, 15)

In [76]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Blood_Group', 'Height_cm', 'Weight_kg',
       'BMI', 'Disease', 'Department', 'City', 'Admission_Date',
       'Discharge_Date', 'Treatment_Cost', 'Insurance_Status', 'Outcome'],
      dtype='object')

In [77]:
df.info

<bound method DataFrame.info of     Patient_ID   Age  Gender Blood_Group  Height_cm  Weight_kg   BMI  \
0        P0001  24.0    Male          A+        162       56.0  21.3
1        P0002  38.0    Male          B+        153       88.0  37.6
2        P0003  18.0    Male          B+        165      102.0  37.5
3        P0004  79.0  Female          O-        161      105.0  40.5
4        P0005  68.0  Female          O+        186      110.0  31.8
..         ...   ...     ...         ...        ...        ...   ...
510      P0010  26.0    Male          O+        177       90.0  28.7
511      P0195  55.0    Male          O-        146       64.0  30.0
512      P0407   NaN  Female         AB+        175       72.0  23.5
513      P0085  59.0  Female          O-        190       45.0  12.5
514      P0372  31.0    Male          B-        156       96.0  39.4

           Disease        Department       City Admission_Date Discharge_Date  \
0         Migraine       Pulmonology    Kolkata     2025-07-28     2025-08-06
1         Diabetes  General Medicine  Hyderabad     2025-10-15     2025-10-26
2           Asthma        Cardiology      Delhi     2025-02-22     2025-02-24
3         COVID-19       Pulmonology      Patna     2025-01-19     2025-01-29
4        Arthritis       Pulmonology       Pune     2025-08-11     2025-08-29
..             ...               ...        ...            ...            ...
510       Diabetes       Pulmonology  Bengaluru     2025-12-29     2026-01-01
511       Migraine  General Medicine     Mumbai     2025-05-16     2025-05-22
512       Migraine        Cardiology  Hyderabad     2025-07-16     2025-07-24
513       Diabetes         Neurology       Pune     2025-12-01     2025-12-16
514  Heart Disease  General Medicine    Kolkata     2025-04-11     2025-04-23

     Treatment_Cost Insurance_Status    Outcome
0           92083.0               No  Recovered
1           27967.0               No  Recovered
2          243852.0               No   Critical
3          143169.0               No  Recovered
4          227125.0              Yes   Critical
..              ...              ...        ...
510         24263.0               No  Recovered
511             NaN              Yes  Recovered
512        244973.0              Yes    Ongoing
513         73031.0              Yes    Ongoing
514        246894.0              Yes  Recovered

[515 rows x 15 columns]>

In [78]:
df.describe

<bound method NDFrame.describe of     Patient_ID   Age  Gender Blood_Group  Height_cm  Weight_kg   BMI  \
0        P0001  24.0    Male          A+        162       56.0  21.3
1        P0002  38.0    Male          B+        153       88.0  37.6
2        P0003  18.0    Male          B+        165      102.0  37.5
3        P0004  79.0  Female          O-        161      105.0  40.5
4        P0005  68.0  Female          O+        186      110.0  31.8
..         ...   ...     ...         ...        ...        ...   ...
510      P0010  26.0    Male          O+        177       90.0  28.7
511      P0195  55.0    Male          O-        146       64.0  30.0
512      P0407   NaN  Female         AB+        175       72.0  23.5
513      P0085  59.0  Female          O-        190       45.0  12.5
514      P0372  31.0    Male          B-        156       96.0  39.4

           Disease        Department       City Admission_Date Discharge_Date  \
0         Migraine       Pulmonology    Kolkata     2025-07-28     2025-08-06
1         Diabetes  General Medicine  Hyderabad     2025-10-15     2025-10-26
2           Asthma        Cardiology      Delhi     2025-02-22     2025-02-24
3         COVID-19       Pulmonology      Patna     2025-01-19     2025-01-29
4        Arthritis       Pulmonology       Pune     2025-08-11     2025-08-29
..             ...               ...        ...            ...            ...
510       Diabetes       Pulmonology  Bengaluru     2025-12-29     2026-01-01
511       Migraine  General Medicine     Mumbai     2025-05-16     2025-05-22
512       Migraine        Cardiology  Hyderabad     2025-07-16     2025-07-24
513       Diabetes         Neurology       Pune     2025-12-01     2025-12-16
514  Heart Disease  General Medicine    Kolkata     2025-04-11     2025-04-23

     Treatment_Cost Insurance_Status    Outcome
0           92083.0               No  Recovered
1           27967.0               No  Recovered
2          243852.0               No   Critical
3          143169.0               No  Recovered
4          227125.0              Yes   Critical
..              ...              ...        ...
510         24263.0               No  Recovered
511             NaN              Yes  Recovered
512        244973.0              Yes    Ongoing
513         73031.0              Yes    Ongoing
514        246894.0              Yes  Recovered

[515 rows x 15 columns]>

In [79]:
df.isnull().sum()

Patient_ID           0
Age                 26
Gender              26
Blood_Group         26
Height_cm            0
Weight_kg           25
BMI                  0
Disease             26
Department           0
City                 0
Admission_Date       0
Discharge_Date       0
Treatment_Cost      27
Insurance_Status     0
Outcome              0
dtype: int64

In [80]:
df.duplicated().sum()

15

In [81]:
df = df.drop_duplicates()

In [82]:
df = df.copy()

df['Admission_Date'] = pd.to_datetime(df['Admission_Date'])
df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date'])

In [83]:
df.isnull().sum()

Patient_ID           0
Age                 25
Gender              25
Blood_Group         25
Height_cm            0
Weight_kg           25
BMI                  0
Disease             25
Department           0
City                 0
Admission_Date       0
Discharge_Date       0
Treatment_Cost      25
Insurance_Status     0
Outcome              0
dtype: int64

In [84]:
# 1 Which disease contributes the highest total treatment cost?

In [85]:
disease_cost = df.groupby('Disease')['Treatment_Cost'].sum().sort_values(ascending=False)
print(disease_cost)

Disease
Asthma           7930109.0
Heart Disease    7849384.0
Arthritis        7611820.0
Diabetes         6776360.0
Pneumonia        6580624.0
COVID-19         6279225.0
Migraine         6234991.0
Hypertension     6213456.0
Name: Treatment_Cost, dtype: float64

In [86]:
# 2 .Which department generates the highest revenue?

In [87]:
dept = df.groupby('Department')['Treatment_Cost'].sum().sort_values(ascending=False)
print(dept)

Department
Neurology           11581883.0
Oncology            11203014.0
Pulmonology          9031911.0
Cardiology           8884038.0
General Medicine     8758748.0
Orthopedics          8650732.0
Name: Treatment_Cost, dtype: float64

In [88]:
# 3. Average treatment cost by disease and insurance status

In [89]:
avg_cost = df.pivot_table(
    values='Treatment_Cost',
    index='Disease',
    columns='Insurance_Status',
    aggfunc='mean'
)
print(avg_cost)

Insurance_Status             No            Yes
Disease
Arthritis         132502.217391  134243.205882
Asthma            114910.052632  118784.233333
COVID-19          115250.038462  136780.166667
Diabetes           94427.961538  130946.454545
Heart Disease     117683.939394  136752.206897
Hypertension      140626.416667  123409.652174
Migraine          110685.689655  151255.300000
Pneumonia         119453.206897  100531.645161

In [90]:
# 4.Percentage of total treatment costs covered by insured patients

In [91]:
total = df['Treatment_Cost'].sum()

insured = df[df['Insurance_Status']=='Yes']['Treatment_Cost'].sum()

percentage = (insured/total)*100

print(f"Percentage Covered: {percentage:.2f}%")

Percentage Covered: 51.22%

In [92]:
# 5. Which city has the highest average treatment cost?

In [93]:
city = df.groupby('City')['Treatment_Cost'].mean().sort_values(ascending=False)
print(city)

City
Delhi        138971.614035
Bengaluru    128442.088235
Kolkata      127484.647059
Mumbai       122903.025641
Hyderabad    119460.600000
Patna        113374.478873
Pune         107740.634921
Name: Treatment_Cost, dtype: float64

In [94]:
bins = [18,30,45,60,100]
labels = ['18-30','31-45','46-60','60+']
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=bins,
    labels=labels,
    include_lowest=True
)
df.head()

,Patient_ID,Age,Gender,Blood_Group,Height_cm,Weight_kg,BMI,Disease,Department,City,Admission_Date,Discharge_Date,Treatment_Cost,Insurance_Status,Outcome,Age_Group
0,P0001,24.0,Male,A+,162,56.0,21.3,Migraine,Pulmonology,Kolkata,2025-07-28,2025-08-06,92083.0,No,Recovered,18-30
1,P0002,38.0,Male,B+,153,88.0,37.6,Diabetes,General Medicine,Hyderabad,2025-10-15,2025-10-26,27967.0,No,Recovered,31-45
2,P0003,18.0,Male,B+,165,102.0,37.5,Asthma,Cardiology,Delhi,2025-02-22,2025-02-24,243852.0,No,Critical,18-30
3,P0004,79.0,Female,O-,161,105.0,40.5,COVID-19,Pulmonology,Patna,2025-01-19,2025-01-29,143169.0,No,Recovered,60+
4,P0005,68.0,Female,O+,186,110.0,31.8,Arthritis,Pulmonology,Pune,2025-08-11,2025-08-29,227125.0,Yes,Critical,60+

In [95]:
# 6. Which age group contributes the highest healthcare expenditure?

In [96]:
age_cost = df.groupby('Age_Group', observed=True)['Treatment_Cost'].sum()
print(age_cost)

Age_Group
18-30    10674465.0
31-45    11909185.0
46-60    13173488.0
60+      19018093.0
Name: Treatment_Cost, dtype: float64

In [97]:
# 7. Most common disease among different age groups

In [98]:
common = (
    df.groupby(['Age_Group', 'Disease'], observed=False)
      .size()
      .reset_index(name='Count')
)
common = common.sort_values(['Age_Group', 'Count'], ascending=[True, False])
print(common)

   Age_Group        Disease  Count
1      18-30         Asthma     14
6      18-30       Migraine     14
0      18-30      Arthritis     13
2      18-30       COVID-19     12
4      18-30  Heart Disease     10
3      18-30       Diabetes      9
5      18-30   Hypertension      9
7      18-30      Pneumonia      9
12     31-45  Heart Disease     15
8      31-45      Arthritis     14
9      31-45         Asthma     13
11     31-45       Diabetes     11
13     31-45   Hypertension     11
15     31-45      Pneumonia     11
10     31-45       COVID-19     10
14     31-45       Migraine      9
16     46-60      Arthritis     20
17     46-60         Asthma     17
19     46-60       Diabetes     16
20     46-60  Heart Disease     15
18     46-60       COVID-19     13
22     46-60       Migraine     13
21     46-60   Hypertension     11
23     46-60      Pneumonia     11
31       60+      Pneumonia     26
25       60+         Asthma     23
27       60+       Diabetes     20
28       60+  Heart Disease     20
26       60+       COVID-19     16
24       60+      Arthritis     15
29       60+   Hypertension     15
30       60+       Migraine     14

In [99]:
#9. Which blood group has the highest incidence of critical outcomes?

In [101]:
critical = df[df['Outcome']=="Critical"]
blood = critical.groupby('Blood_Group').size().sort_values(ascending=False)
print(blood)

Blood_Group
AB-    25
AB+    23
B+     23
O-     22
A+     20
B-     19
A-     16
O+     15
dtype: int64